---
machineset_disable_default_workers: True
machineset_custom_groups:
- name: compute
  autoscale: True
  max_replicas: 6
  min_replicas: 2
  roles:
  - compute
- name: logging-es
  replicas: 1
  roles:
  - logging-es
  provider_spec_override:
    value:
      instanceType: m5.4xlarge

scheduler_default_node_selector: node-role.kubernetes.io/compute=
cluster_autoscaler_cores_min: 16
cluster_autoscaler_cores_max: 256
cluster_autoscaler_memory_min: 8
cluster_autoscaler_memory_max: 512
